### PR TITLE
Silence warning about unused return treated as error due to Werror

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
An (unfortunately) necessary side remark: After receiving the reply on alice-talk that fixing the warnings introduced by their code is not the responsibility of the authors of the code I must say it is very well the responsibility of the authors, and not of annoyed users!

**Comment by kostorr** [comment]
Hello Markus, could you please share the setup that produces these warnings? 

Also, which reply are you referring to?

Cheers,
Kostas

**Comment by mfasDa** [comment]
Hi @kostorr ,

The system is Ubuntu 18.04 with gcc 7.5, and the warning is about unused return value. You might get it under CentOS 8 as well, and due to compilation with Werror the warning will be treated as error. It is rather straight forward to silence, and it is the only warning to be handled in the entire package.

Cheers

Markus

**Review by awegrzyn — CHANGES_REQUESTED** [review]
See https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-ubuntu.html

**Comment by kostorr** [comment]
Hello Markus,

I cannot reproduce these errors on the supported OSs. Anyway ReadoutCard shouldn't be built on Ubuntu in the first place so I have removed it as a dependency for all builds not happening on CentOS, therefore you shouldn't see these anymore. If an issue arises in the future please open a ticket for me on JIRA (https://alice.its.cern.ch/jira/browse/ORC).

Cheers,
Kostas

**Pull request closed without merging**
