### PR TITLE
DO NOT MERGE - CI infrastructure test

### PR DESCRIPTION
**Pull request by TimoWilken**
I'm hoping a new CI worker will pick up this PR. Please don't merge it!

I think I need an approving review for the checker to consider it - @ktf, can you do that?

### CODE REVIEW

**Review by kostorr — APPROVED** [review]

**Comment by TimoWilken** [comment]
Thanks @kostorr!

**Comment by kostorr** [comment]
@TimoWilken I notice this is taking much longer than usual, same for another PR I opened earlier https://github.com/AliceO2Group/ReadoutCard/pull/289

Is something broken?

**Comment by TimoWilken** [comment]
Hi @kostorr, it's working, but I restarted the builders and that wiped out the cache of build artefacts, so the first builds are taking a bit longer. Also, the new workers now build PRs from multiple repos to balance out load, so PRs in ReadoutCard (which doesn't see a huge number of PRs) might take a little longer than usual until we've got the right number of workers figured out. Sorry about that!

The worker that should pick up your PR is up, and it should get round to your PR soon.

**Comment by kostorr** [comment]
No worries, was just curious. Thanks a lot for the info!

**Pull request closed without merging**
