### PR TITLE
[roc-cleanup] Ignore system() return value

### PR DESCRIPTION
**Pull request by kostorr**
Closes ORC-411

### CODE REVIEW

**Comment by kostorr** [comment]
@davidrohr could you check if this suppresses the warnings on your setup? I cannot reproduce it with gcc9.3 on CC7.

**Comment by davidrohr** [comment]
actually, don't we want to check the return values instead of just ignoring them? In the end the warning is there for a reason.
I imagine something like 
```
int retVal = 0;
retVal |= system("rm /var/lib/hugetlbfs/global/pagesize-1GB/roc-bench-dma*");
[...]
if (retVal) throw...
```

**Comment by kostorr** [comment]
In principle I agree. This is expected to fail though, if the files are not there or permissions are not met, and this is absolutely fine, the behaviour of the program doesn't change.

**Comment by davidrohr** [comment]
In that case I'd use `rm -f` but still check the return code?

**Comment by kostorr** [comment]
OK, I updated it to print the ret value in case of a command error. The program will still exit gracefully even if a command failed though. This is necessary for some users of the utility.

**Pull request merged**
